# --use-gl=desktop
# # --use-angle=vulkan
--ozone-platform-hint=auto
--disable-gpu-compositing
# --ignore-gpu-blocklist
# --enable-zero-copy
# --prerender2
# --process-per-site
# --enable-quic
# --enable-gpu-rasterization
# --enable-native-gpu-memory-buffers
# --enable-future-v8-vm-features
# --enable-parallel-downloading
# --enable-features=VaapiVideoDecodeLinuxGL
--enable-wayland-ime
