# --use-gl=desktop
# # --use-angle=vulkan
# --use-cmd-decoder=passthrough
--ozone-platform-hint=auto
--disable-gpu-compositing
# --ignore-gpu-blocklist
# --enable-zero-copy
# --process-per-site
# --enable-gpu-rasterization
# --enable-native-gpu-memory-buffers
# --enable-system-notifications
# # --enable-features=VaapiVideoDecoder,VaapiIgnoreDriverChecks,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE,MiddleClickAutoscroll
# --enable-features=VaapiVideoDecodeLinuxGL
--enable-wayland-ime
