[general]
import = ["themes/tokyonight_moon.toml"]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
dimensions = { columns = 80, lines = 20 }
padding = { x = 0, y = 0 }
dynamic_padding = true
title = "Alacritty"
dynamic_title = true
decorations_theme_variant = "Dark"
resize_increments = true

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "Maple Mono NF", style = "Regular" }
size = 14

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 750
blink_timeout = 5

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "C", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "X", mods = "Control|Shift", action = "Quit" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "Q", mode = "Vi", action = "ToggleViMode" },
]
