#!/usr/bin/env bash

set -e

BASE_PACKAGES=(
	"sof-firmware" "alsa-firmware" "alsa-ucm-conf" "pipewire" "bluez" "bluez-utils" "bluez-obex"
	"alacritty" "kitty" "fish" "zsh" "zsh-completions" "zsh-autosuggestions" "zsh-syntax-highlighting" "bash-completion" "man-db" "git" "wget" "curl" "flatpak" "fuse2" "p7zip" "unrar" "unarchiver" "lzop" "lrzip" "zed" "neovim" "tmux" "xsel" "wl-clipboard" "cliphist" "stow" "starship" "bat" "eza" "fd" "ripgrep" "zoxide" "fzf" "lazygit" "yazi" "bottom" "fastfetch"
	"clang" "cmake" "make" "go" "lua" "luarocks" "nodejs" "npm" "yarn" "pnpm" "ruby" "rust" "rust-analyzer" "docker" "docker-compose" "wrangler" "sassc" "speech-dispatcher" "chafa" "imagemagick" "poppler-glib" "libheif" "ffmpegthumbnailer" "openslide"
	"bash-language-server" "vscode-css-languageserver" "gopls" "vscode-html-languageserver" "vscode-json-languageserver" "lua-language-server" "marksman" "pyright" "ruff" "ruff-lsp" "tailwindcss-language-server" "taplo-cli" "typescript-language-server" "vue-language-server" "yaml-language-server"
	# "gnome" "gnome-tweaks" "gnome-shell-extension-appindicator" "gnome-shell-extension-dash-to-dock"
	"hyprland" "hyprlock" "hypridle" "hyprpaper" "xdg-desktop-portal-hyprland" "archlinux-xdg-menu" "rofi-wayland" "waybar" "inotify-tools" "swww" "dunst" "pavucontrol" "blueman" "network-manager-applet" "polkit-gnome" "gnome-keyring" "grim" "slurp" "nautilus" "loupe" "ly"
	"fcitx5-im" "fcitx5-rime" "fcitx5-chinese-addons" "fcitx5-material-color" "fcitx5-pinyin-zhwiki"
	"firefox" "chromium" "gnome-system-monitor" "solaar" "mpv" "libreoffice-still"
	"adobe-source-han-serif-cn-fonts" "wqy-zenhei" "noto-fonts" "noto-fonts-cjk" "noto-fonts-emoji" "noto-fonts-extra" "inter-font"
	"papirus-icon-theme" "adwaita-icon-theme" "gnome-themes-standard" "gnome-themes-extra" "nwg-look" "gtk-engine-murrine" "qt5-wayland" "qt6-wayland" "qt6ct" "xorg-xrdb"
)
AUR_HELPER="paru"
AUR_PACKAGES=("mkinitcpio-firmware" "xray" "v2raya" "wechat-universal-bwrap")
AUR_PACKAGES+=("wlogout" "hyprpicker" "hyprshade")

ENABLE_INTEL_GRAPHICS=true
ENABLE_NVIDIA_GRAPHICS=true

# Pacman options
sudo sed -i "s/#Color/Color/g" /etc/pacman.conf
sudo sed -i "s/#ParallelDownloads/ParallelDownloads/g" /etc/pacman.conf

# Archlinuxcn
pacman_conf="/etc/pacman.conf"
archlinuxcn_name="archlinuxcn"
archlinuxcn_server="https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/\$arch"

if ! grep -q "\[${archlinuxcn_name}\]" "$pacman_conf"; then
	echo "[${archlinuxcn_name}]" | sudo tee -a "$pacman_conf" >/dev/null
	echo "Server = ${archlinuxcn_server}" | sudo tee -a "$pacman_conf" >/dev/null
	sudo pacman-key --lsign-key "farseerfc@archlinux.org"
	sudo pacman -Sy --noconfirm archlinuxcn-keyring
fi

# Update system and install packages
sudo pacman -Syyu --noconfirm
sudo pacman -S --needed --noconfirm "${BASE_PACKAGES[@]}"

# Intel drivers
if $ENABLE_INTEL_GRAPHICS; then
	sudo pacman -S --noconfirm --needed mesa lib32-mesa vulkan-intel lib32-vulkan-intel intel-gpu-tools libva-utils
fi

# Nvidia drivers
if $ENABLE_NVIDIA_GRAPHICS; then
	sudo pacman -S --noconfirm --needed nvidia nvidia-settings nvidia-utils lib32-nvidia-utils libva-nvidia-driver egl-wayland nvidia-prime

	# Pass parameters to nvidia module
	echo "options nvidia_drm modeset=1 fbdev=1" | sudo tee -a "/etc/modprobe.d/nvidia.conf"
	echo "options nvidia NVreg_PreserveVideoMemoryAllocations=1" | sudo tee -a "/etc/modprobe.d/nvidia-power-management.conf"

	# Early load nvidia modules
	mkinitcpio_conf="/etc/mkinitcpio.conf"
	if ! grep -q "^MODULES=.*nvidia" "$mkinitcpio_conf"; then
		sudo sed -i '/^MODULES=/ s/(\(.*\))/(\1 nvidia nvidia_modeset nvidia_uvm nvidia_drm)/' "$mkinitcpio_conf"
		sudo sed -i '/HOOKS/ s/kms//g' "$mkinitcpio_conf"
		sudo mkinitcpio -P
	fi

	# Preserve video memory after suspend
	sudo systemctl enable nvidia-suspend.service
	sudo systemctl enable nvidia-hibernate.service
	sudo systemctl enable nvidia-resume.service

	# Force-enable Wayland
	sudo ln -sf /dev/null /etc/udev/rules.d/61-gdm.rules
fi

# Automatically unlock the gnome-keyring
PAM_FILE="/etc/pam.d/login"
sudo grep -qxF 'auth optional pam_gnome_keyring.so' "$PAM_FILE" || sudo sh -c "echo 'auth optional pam_gnome_keyring.so' >> $PAM_FILE"
sudo grep -qxF 'session optional pam_gnome_keyring.so auto_start' "$PAM_FILE" || sudo sh -c "echo 'session optional pam_gnome_keyring.so auto_start' >> $PAM_FILE"

# Automatically change keyring password with user password
sudo grep -qxF "password optional pam_gnome_keyring.so" "$PAM_FILE" || sudo sh -c "echo 'password optional pam_gnome_keyring.so' >>/etc/pam.d/passwd"

bash "$HOME/.dotfiles/bin/.local/bin/stow-packages"
bash "$HOME/.dotfiles/bin/.local/bin/mkdir-local"
bash "$HOME/.dotfiles/bin/.local/bin/install-flatpak"
bash "$HOME/.dotfiles/bin/.local/bin/install-fcitx5"
bash "$HOME/.dotfiles/bin/.local/bin/install-fonts"
bash "$HOME/.dotfiles/bin/.local/bin/install-themes"
bash "$HOME/.dotfiles/bin/.local/bin/install-wallpapaers"
bash "$HOME/.dotfiles/bin/.local/bin/dconf-restore"
bash "$HOME/.dotfiles/bin/.local/bin/stow-packages"
bash "$HOME/.dotfiles/bin/.local/bin/dns"

# Install AUR helper
if ! command -v $AUR_HELPER &>/dev/null; then
	if pacman -Ss "^${AUR_HELPER}$" >/dev/null 2>&1; then
		sudo pacman -S --needed --noconfirm "$AUR_HELPER"
	else
		pushd /tmp
		git clone --depth=1 https://aur.archlinux.org/$AUR_HELPER.git
		cd $AUR_HELPER && makepkg -si
		popd
	fi
fi

# Install aur packages
sh -c "$AUR_HELPER -S --needed --noconfirm ${AUR_PACKAGES[*]}"

# Enable system services
sudo systemctl enable --now bluetooth
sudo systemctl enable --now docker
sudo systemctl enable --now xray
sudo systemctl enable --now v2raya
# sudo systemctl enable ly

sudo usermod -aG docker "$USER"

echo "FONT=ter-132n" | sudo tee -a /etc/vconsole.conf
