#!/usr/bin/env bash

sudo dnf upgrade -y && sudo dnf install -y \
	alacritty zsh fish bash-completion stow neovim xsel wl-clipboard tmux \
	bat eza zoxide fd-find ripgrep fzf fastfetch luarocks yarnpkg ruby golang cargo sassc openslide-tools \
	gnome-tweaks gnome-extensions-app gnome-shell-extension-appindicator gnome-shell-extension-user-theme \
	gnome-shell-extension-blur-my-shell gnome-shell-extension-dash-to-dock gnome-themes-extra gtk-murrine-engine \
	fcitx5 fcitx5-qt fcitx5-lua fcitx5-rime fcitx5-gtk fcitx5-configtool fcitx5-autostart fcitx5-chinese-addons \
	rsms-inter-fonts papirus-icon-theme mpv solaar xrandr \
	igt-gpu-tools akmod-nvidia xorg-x11-drv-nvidia-cuda xorg-x11-drv-nvidia-cuda-libs xorg-x11-drv-nvidia-power \
	vulkan nvidia-vaapi-driver libva-utils vdpauinfo

sudo dnf mark install akmod-nvidia
sudo systemctl enable nvidia-{suspend,resume,hibernate}

stow -v git bin

bash "$HOME/.dotfiles/bin/.local/bin/mkdir-local"
bash "$HOME/.dotfiles/bin/.local/bin/github520"
bash "$HOME/.dotfiles/bin/.local/bin/install-flatpak"
bash "$HOME/.dotfiles/bin/.local/bin/install-fcitx5"
bash "$HOME/.dotfiles/bin/.local/bin/install-themes"
bash "$HOME/.dotfiles/bin/.local/bin/dconf-restore"
bash "$HOME/.dotfiles/bin/.local/bin/stow-packages"
bash "$HOME/.dotfiles/bin/.local/bin/dns"

# v2raya
sudo dnf copr enable zhullyb/v2rayA
sudo dnf install -y v2raya
sudo systemctl enable --now v2raya

# lazygit
sudo dnf copr enable atim/lazygit -y
sudo dnf install -y lazygit

# Cursor theme
sudo dnf copr enable peterwu/rendezvous
sudo dnf install -y bibata-cursor-themes
# curl -sS https://starship.rs/install.sh | sh
