#!/usr/bin/env bash

set -e

PACKAGES=(
	"alacritty" "zsh" "fish" "bash-completion" "curl" "unzip" "stow" "bat" "eza" "zoxide" "fd-find" "ripgrep" "fzf" "neovim" "xsel" "wl-clipboard"
	"build-essential" "cmake" "python3" "python3-pip" "python3.12-venv" "luarocks" "ruby" "nodejs" "npm" "yarnpkg" "golang" "rust-all" "sassc" "openslide-tools"
	"fcitx5" "fcitx5-chinese-addons" "fcitx5-material-color" "fcitx5-rime" "fcitx5-table-emoji" "fcitx5-module-emoji" "fcitx5-config-qt" fcitx5-frontend-{gtk3,gtk4,qt5}
	"gnome-tweaks" "gnome-shell-extensions" "gnome-shell-extension-manager" "gtk2-engines-murrine" "gnome-themes-extra" "papirus-icon-theme"
	"fonts-noto" "fonts-wqy-zenhei" "fonts-wqy-microhei" "fonts-inter" "gpick" "gimp" "solaar" "flatpak" "gnome-software-plugin-flatpak"
)

sudo apt update && sudo apt upgrade
sudo apt install -y "${PACKAGES[@]}"

bash "$HOME/.dotfiles/bin/.local/bin/stow-packages"
bash "$HOME/.dotfiles/bin/.local/bin/mkdir-local"
bash "$HOME/.dotfiles/bin/.local/bin/github520"
bash "$HOME/.dotfiles/bin/.local/bin/install-flatpak"
bash "$HOME/.dotfiles/bin/.local/bin/install-fcitx5"
bash "$HOME/.dotfiles/bin/.local/bin/install-v2raya"
bash "$HOME/.dotfiles/bin/.local/bin/install-fonts"
bash "$HOME/.dotfiles/bin/.local/bin/install-themes"
bash "$HOME/.dotfiles/bin/.local/bin/install-wallpapaers"
bash "$HOME/.dotfiles/bin/.local/bin/dconf-restore"
bash "$HOME/.dotfiles/bin/.local/bin/dns"
bash "$HOME/.dotfiles/bin/.local/bin/stow-packages"

# curl -sS https://starship.rs/install.sh | sh
# go install github.com/jesseduffield/lazygit@latest
# git clone --depth 1 https://github.com/junegunn/fzf.git" "$HOME/.fzf"
# "$HOME"/.fzf/install
