# GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
# XMODIFIERS=@im=fcitx
SDL_IM_MODULE=fcitx
INPUT_METHOD=fcitx
GLFW_IM_MODULE=ibus

# LIBVA_DRIVER_NAME=nvidia
# XDG_SESSION_TYPE=wayland
# GBM_BACKEND=nvidia-drm
# __GLX_VENDOR_LIBRARY_NAME=nvidia
# NVD_BACKEND=direct

XCURSOR_THEME="Bibata-Modern-Ice"
